from enum import IntEnum
from typing import Self, TYPE_CHECKING

from talon import app

if app.platform == "windows" or TYPE_CHECKING:
    import win32con

    from ..lib.winapi import oleacc, user32
else:
    raise NotImplementedError("Unsupported OS.")


class _FromStrMixin:
    @staticmethod
    def _get_label_and_prefix() -> tuple[str, str]:
        return ("[label]", "[prefix]")

    @classmethod
    def from_str(cls, name: str) -> Self:
        try:
            return cls.__members__[name]
        except KeyError:
            label, prefix = cls._get_label_and_prefix()
            raise ValueError(
                f"Unexpected {label} constant `{name}`."
                + (
                    f" Note that the `{prefix}` prefix must be omitted."
                    if name.startswith(prefix)
                    else ""
                )
            )


class WinEvent(_FromStrMixin, IntEnum):
    """Win event constants without the `EVENT_` prefix. See <https://learn.microsoft.com/en-us/windows/win32/winauto/event-constants>."""

    @staticmethod
    def _get_label_and_prefix() -> tuple[str, str]:
        return ("event", "EVENT_")

    MIN = win32con.EVENT_MIN
    MAX = win32con.EVENT_MAX
    SYSTEM_SOUND = win32con.EVENT_SYSTEM_SOUND
    SYSTEM_ALERT = win32con.EVENT_SYSTEM_ALERT
    SYSTEM_FOREGROUND = win32con.EVENT_SYSTEM_FOREGROUND
    SYSTEM_MENUSTART = win32con.EVENT_SYSTEM_MENUSTART
    SYSTEM_MENUEND = win32con.EVENT_SYSTEM_MENUEND
    SYSTEM_MENUPOPUPSTART = win32con.EVENT_SYSTEM_MENUPOPUPSTART
    SYSTEM_MENUPOPUPEND = win32con.EVENT_SYSTEM_MENUPOPUPEND
    SYSTEM_CAPTURESTART = win32con.EVENT_SYSTEM_CAPTURESTART
    SYSTEM_CAPTUREEND = win32con.EVENT_SYSTEM_CAPTUREEND
    SYSTEM_MOVESIZESTART = win32con.EVENT_SYSTEM_MOVESIZESTART
    SYSTEM_MOVESIZEEND = win32con.EVENT_SYSTEM_MOVESIZEEND
    SYSTEM_CONTEXTHELPSTART = win32con.EVENT_SYSTEM_CONTEXTHELPSTART
    SYSTEM_CONTEXTHELPEND = win32con.EVENT_SYSTEM_CONTEXTHELPEND
    SYSTEM_DRAGDROPSTART = win32con.EVENT_SYSTEM_DRAGDROPSTART
    SYSTEM_DRAGDROPEND = win32con.EVENT_SYSTEM_DRAGDROPEND
    SYSTEM_DIALOGSTART = win32con.EVENT_SYSTEM_DIALOGSTART
    SYSTEM_DIALOGEND = win32con.EVENT_SYSTEM_DIALOGEND
    SYSTEM_SCROLLINGSTART = win32con.EVENT_SYSTEM_SCROLLINGSTART
    SYSTEM_SCROLLINGEND = win32con.EVENT_SYSTEM_SCROLLINGEND
    SYSTEM_SWITCHSTART = win32con.EVENT_SYSTEM_SWITCHSTART
    SYSTEM_SWITCHEND = win32con.EVENT_SYSTEM_SWITCHEND
    SYSTEM_MINIMIZESTART = win32con.EVENT_SYSTEM_MINIMIZESTART
    SYSTEM_MINIMIZEEND = win32con.EVENT_SYSTEM_MINIMIZEEND
    SYSTEM_DESKTOPSWITCH = user32.EVENT_SYSTEM_DESKTOPSWITCH
    SYSTEM_SWITCHER_APPGRABBED = user32.EVENT_SYSTEM_SWITCHER_APPGRABBED
    SYSTEM_SWITCHER_APPOVERTARGET = user32.EVENT_SYSTEM_SWITCHER_APPOVERTARGET
    SYSTEM_SWITCHER_APPDROPPED = user32.EVENT_SYSTEM_SWITCHER_APPDROPPED
    SYSTEM_SWITCHER_CANCELLED = user32.EVENT_SYSTEM_SWITCHER_CANCELLED
    SYSTEM_IME_KEY_NOTIFICATION = user32.EVENT_SYSTEM_IME_KEY_NOTIFICATION
    SYSTEM_END = user32.EVENT_SYSTEM_END
    OEM_DEFINED_START = user32.EVENT_OEM_DEFINED_START
    OEM_DEFINED_END = user32.EVENT_OEM_DEFINED_END
    UIA_EVENTID_START = user32.EVENT_UIA_EVENTID_START
    UIA_EVENTID_END = user32.EVENT_UIA_EVENTID_END
    UIA_PROPID_START = user32.EVENT_UIA_PROPID_START
    UIA_PROPID_END = user32.EVENT_UIA_PROPID_END
    CONSOLE_CARET = user32.EVENT_CONSOLE_CARET
    CONSOLE_UPDATE_REGION = user32.EVENT_CONSOLE_UPDATE_REGION
    CONSOLE_UPDATE_SIMPLE = user32.EVENT_CONSOLE_UPDATE_SIMPLE
    CONSOLE_UPDATE_SCROLL = user32.EVENT_CONSOLE_UPDATE_SCROLL
    CONSOLE_LAYOUT = user32.EVENT_CONSOLE_LAYOUT
    CONSOLE_START_APPLICATION = user32.EVENT_CONSOLE_START_APPLICATION
    CONSOLE_END_APPLICATION = user32.EVENT_CONSOLE_END_APPLICATION
    CONSOLE_END = user32.EVENT_CONSOLE_END
    OBJECT_CREATE = win32con.EVENT_OBJECT_CREATE
    OBJECT_DESTROY = win32con.EVENT_OBJECT_DESTROY
    OBJECT_SHOW = win32con.EVENT_OBJECT_SHOW
    OBJECT_HIDE = win32con.EVENT_OBJECT_HIDE
    OBJECT_REORDER = win32con.EVENT_OBJECT_REORDER
    OBJECT_FOCUS = win32con.EVENT_OBJECT_FOCUS
    OBJECT_SELECTION = win32con.EVENT_OBJECT_SELECTION
    OBJECT_SELECTIONADD = win32con.EVENT_OBJECT_SELECTIONADD
    OBJECT_SELECTIONREMOVE = win32con.EVENT_OBJECT_SELECTIONREMOVE
    OBJECT_SELECTIONWITHIN = win32con.EVENT_OBJECT_SELECTIONWITHIN
    OBJECT_STATECHANGE = win32con.EVENT_OBJECT_STATECHANGE
    OBJECT_LOCATIONCHANGE = win32con.EVENT_OBJECT_LOCATIONCHANGE
    OBJECT_NAMECHANGE = win32con.EVENT_OBJECT_NAMECHANGE
    OBJECT_DESCRIPTIONCHANGE = win32con.EVENT_OBJECT_DESCRIPTIONCHANGE
    OBJECT_VALUECHANGE = win32con.EVENT_OBJECT_VALUECHANGE
    OBJECT_PARENTCHANGE = win32con.EVENT_OBJECT_PARENTCHANGE
    OBJECT_HELPCHANGE = win32con.EVENT_OBJECT_HELPCHANGE
    OBJECT_DEFACTIONCHANGE = win32con.EVENT_OBJECT_DEFACTIONCHANGE
    OBJECT_ACCELERATORCHANGE = win32con.EVENT_OBJECT_ACCELERATORCHANGE
    OBJECT_INVOKED = user32.EVENT_OBJECT_INVOKED
    OBJECT_TEXTSELECTIONCHANGED = user32.EVENT_OBJECT_TEXTSELECTIONCHANGED
    OBJECT_CONTENTSCROLLED = user32.EVENT_OBJECT_CONTENTSCROLLED
    SYSTEM_ARRANGMENTPREVIEW = user32.EVENT_SYSTEM_ARRANGMENTPREVIEW
    OBJECT_CLOAKED = user32.EVENT_OBJECT_CLOAKED
    OBJECT_UNCLOAKED = user32.EVENT_OBJECT_UNCLOAKED
    OBJECT_LIVEREGIONCHANGED = user32.EVENT_OBJECT_LIVEREGIONCHANGED
    OBJECT_HOSTEDOBJECTSINVALIDATED = user32.EVENT_OBJECT_HOSTEDOBJECTSINVALIDATED
    OBJECT_DRAGSTART = user32.EVENT_OBJECT_DRAGSTART
    OBJECT_DRAGCANCEL = user32.EVENT_OBJECT_DRAGCANCEL
    OBJECT_DRAGCOMPLETE = user32.EVENT_OBJECT_DRAGCOMPLETE
    OBJECT_DRAGENTER = user32.EVENT_OBJECT_DRAGENTER
    OBJECT_DRAGLEAVE = user32.EVENT_OBJECT_DRAGLEAVE
    OBJECT_DRAGDROPPED = user32.EVENT_OBJECT_DRAGDROPPED
    OBJECT_IME_SHOW = user32.EVENT_OBJECT_IME_SHOW
    OBJECT_IME_HIDE = user32.EVENT_OBJECT_IME_HIDE
    OBJECT_IME_CHANGE = user32.EVENT_OBJECT_IME_CHANGE
    OBJECT_TEXTEDIT_CONVERSIONTARGETCHANGED = user32.EVENT_OBJECT_TEXTEDIT_CONVERSIONTARGETCHANGED
    OBJECT_END = user32.EVENT_OBJECT_END
    AIA_START = user32.EVENT_AIA_START
    AIA_END = user32.EVENT_AIA_END


class ObjectID(_FromStrMixin, IntEnum):
    """Object ID constants without the `OBJID_` prefix. See <https://learn.microsoft.com/en-us/windows/win32/winauto/object-identifiers>."""

    @staticmethod
    def _get_label_and_prefix() -> tuple[str, str]:
        return ("object ID", "OBJID_")

    WINDOW = win32con.OBJID_WINDOW
    SYSMENU = win32con.OBJID_SYSMENU
    TITLEBAR = win32con.OBJID_TITLEBAR
    MENU = win32con.OBJID_MENU
    CLIENT = win32con.OBJID_CLIENT
    VSCROLL = win32con.OBJID_VSCROLL
    HSCROLL = win32con.OBJID_HSCROLL
    SIZEGRIP = win32con.OBJID_SIZEGRIP
    CARET = win32con.OBJID_CARET
    CURSOR = win32con.OBJID_CURSOR
    ALERT = win32con.OBJID_ALERT
    SOUND = win32con.OBJID_SOUND
    QUERYCLASSNAMEIDX = user32.OBJID_QUERYCLASSNAMEIDX
    NATIVEOM = user32.OBJID_NATIVEOM


class Role(_FromStrMixin, IntEnum):
    """Role constants without the `ROLE_SYSTEM_` prefix. See <https://learn.microsoft.com/en-us/windows/win32/winauto/object-roles>."""

    @staticmethod
    def _get_label_and_prefix() -> tuple[str, str]:
        return ("role", "ROLE_SYSTEM_")

    TITLEBAR = oleacc.ROLE_SYSTEM_TITLEBAR
    MENUBAR = oleacc.ROLE_SYSTEM_MENUBAR
    SCROLLBAR = oleacc.ROLE_SYSTEM_SCROLLBAR
    GRIP = oleacc.ROLE_SYSTEM_GRIP
    SOUND = oleacc.ROLE_SYSTEM_SOUND
    CURSOR = oleacc.ROLE_SYSTEM_CURSOR
    CARET = oleacc.ROLE_SYSTEM_CARET
    ALERT = oleacc.ROLE_SYSTEM_ALERT
    WINDOW = oleacc.ROLE_SYSTEM_WINDOW
    CLIENT = oleacc.ROLE_SYSTEM_CLIENT
    MENUPOPUP = oleacc.ROLE_SYSTEM_MENUPOPUP
    MENUITEM = oleacc.ROLE_SYSTEM_MENUITEM
    TOOLTIP = oleacc.ROLE_SYSTEM_TOOLTIP
    APPLICATION = oleacc.ROLE_SYSTEM_APPLICATION
    DOCUMENT = oleacc.ROLE_SYSTEM_DOCUMENT
    PANE = oleacc.ROLE_SYSTEM_PANE
    CHART = oleacc.ROLE_SYSTEM_CHART
    DIALOG = oleacc.ROLE_SYSTEM_DIALOG
    BORDER = oleacc.ROLE_SYSTEM_BORDER
    GROUPING = oleacc.ROLE_SYSTEM_GROUPING
    SEPARATOR = oleacc.ROLE_SYSTEM_SEPARATOR
    TOOLBAR = oleacc.ROLE_SYSTEM_TOOLBAR
    STATUSBAR = oleacc.ROLE_SYSTEM_STATUSBAR
    TABLE = oleacc.ROLE_SYSTEM_TABLE
    COLUMNHEADER = oleacc.ROLE_SYSTEM_COLUMNHEADER
    ROWHEADER = oleacc.ROLE_SYSTEM_ROWHEADER
    COLUMN = oleacc.ROLE_SYSTEM_COLUMN
    ROW = oleacc.ROLE_SYSTEM_ROW
    CELL = oleacc.ROLE_SYSTEM_CELL
    LINK = oleacc.ROLE_SYSTEM_LINK
    HELPBALLOON = oleacc.ROLE_SYSTEM_HELPBALLOON
    CHARACTER = oleacc.ROLE_SYSTEM_CHARACTER
    LIST = oleacc.ROLE_SYSTEM_LIST
    LISTITEM = oleacc.ROLE_SYSTEM_LISTITEM
    OUTLINE = oleacc.ROLE_SYSTEM_OUTLINE
    OUTLINEITEM = oleacc.ROLE_SYSTEM_OUTLINEITEM
    PAGETAB = oleacc.ROLE_SYSTEM_PAGETAB
    PROPERTYPAGE = oleacc.ROLE_SYSTEM_PROPERTYPAGE
    INDICATOR = oleacc.ROLE_SYSTEM_INDICATOR
    GRAPHIC = oleacc.ROLE_SYSTEM_GRAPHIC
    STATICTEXT = oleacc.ROLE_SYSTEM_STATICTEXT
    TEXT = oleacc.ROLE_SYSTEM_TEXT
    PUSHBUTTON = oleacc.ROLE_SYSTEM_PUSHBUTTON
    CHECKBUTTON = oleacc.ROLE_SYSTEM_CHECKBUTTON
    RADIOBUTTON = oleacc.ROLE_SYSTEM_RADIOBUTTON
    COMBOBOX = oleacc.ROLE_SYSTEM_COMBOBOX
    DROPLIST = oleacc.ROLE_SYSTEM_DROPLIST
    PROGRESSBAR = oleacc.ROLE_SYSTEM_PROGRESSBAR
    DIAL = oleacc.ROLE_SYSTEM_DIAL
    HOTKEYFIELD = oleacc.ROLE_SYSTEM_HOTKEYFIELD
    SLIDER = oleacc.ROLE_SYSTEM_SLIDER
    SPINBUTTON = oleacc.ROLE_SYSTEM_SPINBUTTON
    DIAGRAM = oleacc.ROLE_SYSTEM_DIAGRAM
    ANIMATION = oleacc.ROLE_SYSTEM_ANIMATION
    EQUATION = oleacc.ROLE_SYSTEM_EQUATION
    BUTTONDROPDOWN = oleacc.ROLE_SYSTEM_BUTTONDROPDOWN
    BUTTONMENU = oleacc.ROLE_SYSTEM_BUTTONMENU
    BUTTONDROPDOWNGRID = oleacc.ROLE_SYSTEM_BUTTONDROPDOWNGRID
    WHITESPACE = oleacc.ROLE_SYSTEM_WHITESPACE
    PAGETABLIST = oleacc.ROLE_SYSTEM_PAGETABLIST
    CLOCK = oleacc.ROLE_SYSTEM_CLOCK
    SPLITBUTTON = oleacc.ROLE_SYSTEM_SPLITBUTTON
    IPADDRESS = oleacc.ROLE_SYSTEM_IPADDRESS
    OUTLINEBUTTON = oleacc.ROLE_SYSTEM_OUTLINEBUTTON
